services:
  - name: userlink-chatroom-api
    type: web
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true 